:sectlinks:
:sectanchors:
:stylesheet: asciidoctor.css
:imagesdir: ./images
// If not rendered on github, we use fonts for the captions, otherwise, we assign github emojis. DO NOT PUT A BLANK LINE BEFORE THIS, the ICONS don't render.
ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:important-caption: :exclamation:
:warning-caption: :x:
:caution-caption: :hand:
:note-caption: :bulb:
:tip-caption: :mag:
endif::[]

= Spring Cloud Data Flow Kubernetes Setup

These are my notes on using the provided helm chart for Spring Cloud Data Flow to install a working instance within Kubernetes. The chart
provides a large number of configuration options and we are going to make changes such that the data flow server uses MS SQL Server rather
than Mariadb. 

== Add SCDF Chart repository to the Helm Client

These notes assume you have helm correctly installed on your machine and you have configured kubectl to point to the correct Kubernetes context.
The chart for SCDF has recently moved to bitnami and the first step is to add bitnami's repository to helm:

`helm repo add bitnami https://charts.bitnami.com/bitnami`

NOTE: The steps taken here losely follow the https://dataflow.spring.io/docs/installation/kubernetes/helm/[installation documentation on Spring's official web site]. The documentation (at the time of this writing) does not match exactly with the chart that is hosted on Bitnami.


== Structure of the SCDF Helm Chart

The helm chart can be viewed via github at https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow[https://github.com/bitnami/charts/tree/master/bitnami/spring-cloud-dataflow]
and the `README.md` contains documentation for the various customizations that can be made to the helm chart.


Ultimately, the chart will be installed with the following command (All customizations will be defined in the settings file) : 

`helm install --name my-release -f ./scdf-settings.yaml bitnami/spring-cloud-dataflow`

== Customizing the SCDF Helm Chart

Installing the chart into a kubernetes cluster on a developer's machine requires exposing a NodePort to allow an external web client to access the data flow server.
The chart provides the ability to do this by specifying the following in the settings file. If you are using the Kubernetes cluster that is packages with docker
desktop, after the chart is installed, the data flow server can be accessed via `http://localhost:30100/dashboard`:

scdf-settings.yml
```
server:
  service:
    # We want to expose the data flow server on an external node port, so we can access it from a browser.
    type: NodePort
    nodePort: 30100
```

== Using a custom database with data flow.

The helm chart is pre-configured to install a mariadb inside the kubernetes cluster that will be used to persist job/task information. This makes it easy to setup the data flow server for experimentation but you will likely want to connect the server to a managed/external database.

In this example, we will configure the chart to connect to an MS SQL Server database. These instructions assume the DNS for the database server can be resolved from within the Kubernetes cluster.

NOTE: If you are using a database server that is hosted within a private data center, link:../../README{outfilesuffix}#kubernetes-dns-setup[please see the sections on extending CoreDNS].

NOTE: If you want to experiment with MS SQL Server, you can follow the link:../sql-server/sql-server-on-kubernetes{outfilesuffix}[sql-server recipe]. After SQL Server is running within the cluster, pods within the cluster can use the DNS `mssql-server` to connect to the database server.

There are many wants to inject database configuration into the data flow server, this document will outline two methods that I have tried.

=== Using the "externalDatabase" properties to connect to the database.

The official Helm chart for Spring Cloud Data Flow provides the ability to customize the database connectivity via pre-defined properties. If the sql server DNS name is `mssql-server`, the following can be added to the `scdf-settings.yml` file:

scdf-settings.yml
```
externalDatabase:
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  password: "Coolpass1!"
  dataflow:
    url : "jdbc:sqlserver://mssql-server" # <1>
    user: dataflow
  skipper:
    url : "jdbc:sqlserver://mssql-server" # <1>
    user: dataflow
  hibernateDialect: "org.hibernate.dialect.SQLServer2012Dialect" # <2>

# Disabling MariaDB
mariadb:
  enabled: false # <3>
```
<1> The jdbc url must be specified for both the data flow server and skipper (if you are going to use the streaming capabilities of dataflow)
<2> The data flow server uses Hibernate and we need to specific the correct SQL dialect.
<3> Finally, you must tell the chart to NOT provision the MariaDB pod as part of the deployment.

=== Using an external Spring Cloud Config server to provide configuration.

The Spring Cloud Config server is a great way to serve configuration information into any Spring Boot enabled application. This means that SCDF can be configured to pick-up its configuration information from a config server. To set this up, several envrionment variables need to be configured in the `scdf-settings.yml` file. These environment variables are mounted into the Spring Environment of the data flow server.

```
server:
  # We can set environment variables directly from this helm chart.
  extraEnvVars:
  - name: "SPRING_CLOUD_CONFIG_ENABLED"
    value: "true" <1>
  - name: "SPRING_CLOUD_CONFIG_NAME"
    value: "data-flow" <2>
  - name: "SPRING_CLOUD_CONFIG_URI"
    value: "http://config" <3>
  - name: "SPRING_CLOUD_CONFIG_LABEL"
    value: "SODEV-28877" <4>
  - name: "SPRING_CLOUD_CONFIG_USERNAME"
    value: "config"
  - name: "SPRING_CLOUD_CONFIG_PASSWORD"
    value: "Cheve1le!"
# Disabling MariaDB
mariadb:
  enabled: false <5>
```
<1> The data flow server must have the spring-cloud-client explicitly enabled to use the config server.
<2> The application name used by the data flow server when retrieving information from the config server.
<3> The URL used to connect to the config server. This must be a dns host that is resolvable within the Kubenetes cluster.
<4> If the configuration settings are NOT on the main branch, a branch label can be specified.
<5> The MariaDB must be disabled to ensure it is not provisioned as part of the Helm chart.

Once the chart environemnt has been setup to connect to the configuration server, the configuration can be setup like any other application:

```
---

spring:
  datasource:
    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    url: "jdbc:sqlserver://mssql-server"
    user: "dataflow"
    password: "Coolpass1!"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.SQLServer2012Dialect"
```
